version: '3.1'
services:
  zk1:
    image: confluentinc/cp-zookeeper:6.0.0
    container_name: zk1
    environment:
        ZOOKEEPER_CLIENT_PORT: "2181"
        ZOOKEEPER_SERVER_ID: "1"

  zk2:
    image: confluentinc/cp-zookeeper:6.0.0
    container_name: zk2
    environment:
        ZOOKEEPER_CLIENT_PORT: "2181"
        ZOOKEEPER_SERVER_ID: "2"

  zk3:
    image: confluentinc/cp-zookeeper:6.0.0
    container_name: zk3
    environment:
        ZOOKEEPER_CLIENT_PORT: "2181"
        ZOOKEEPER_SERVER_ID: "3"

  kafka1:
    build: 
      context: ./kafka
      args:
        truststore: certs/kafka1/kafka.server.truststore.jks
        keystore: certs/kafka1/kafka.server.keystore.jks
    container_name: kafka1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka1:9092
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.server.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka_sslkey_creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka_sslkey_creds
      KAFKA_SSL_CLIENT_AUTH: required
    ports:
      - '9092:9092'

  kafka2:
    build: 
      context: ./kafka
      args:
        truststore: certs/kafka2/kafka.server.truststore.jks
        keystore: certs/kafka2/kafka.server.keystore.jks
    container_name: kafka2
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka2:9093
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.server.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka_sslkey_creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka_sslkey_creds
      KAFKA_SSL_CLIENT_AUTH: required
    ports:
      - '9093:9093'

  kafka3:
    build: 
      context: ./kafka
      args:
        truststore: certs/kafka3/kafka.server.truststore.jks
        keystore: certs/kafka3/kafka.server.keystore.jks
    container_name: kafka3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka1:9094
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.server.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka_sslkey_creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka_sslkey_creds
      KAFKA_SSL_CLIENT_AUTH: required
    ports:
      - '9094:9094'